const mongoose = require("mongoose");

const Schema = mongoose.Schema; // .Schema is a class present in a mongoose

const bookSchema = new Schema(
  {
    // create schemaa for books

    // here we are not making field for Id because, id is auto generated by mongoose & it act as a Primary key
    name: {
      type: String,
      required: true,
    },
    author: {
      type: String,
      required: true,
    },
    grnre: {
      type: String,
      required: true,
    },
    price: {
      type: String,
      required: true,
    },
    publisher: {
      type: String,
      required: true,
    },
  },
  // adding an extra field
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Book", bookSchema);
