const mongoose = require("mongoose");

const Schema = mongoose.Schema; // .Schema is a Class present in a mongoose

const userSchema = new Schema(
  {
    // create schema for users

    // here also we didn't make any field for the id because, its auto generated by mogoose & it act as a Primary key

    name: {
      type: String,
      required: true,
    },
    surname: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
    },
    // Reference integrity from Book table
    issuedBook: {
      type: mongoose.Schema.Types.ObjectId, // this way we declare the foreign key
      ref: "Book", // having reference from
      required: false,
    },
    issuedDate: {
      type: String,
      required: false,
    },
    returnDate: {
      type: String,
      required: false,
    },
    subscriptionType: {
      type: String,
      required: true,
    },
    subscriptionDate: {
      type: String,
      required: true,
    },
  },
  // adding extra fiels
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("User", userSchema);
